/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import CRUD.CRUDEncargado;
import Controlador.Conexion;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author angel
 */
public class VEncargado extends javax.swing.JFrame {

    /**
     * Creates new form VEncargado
     */

    Conexion conexion = new Conexion();
    CRUDEncargado encargado = new CRUDEncargado(conexion.conectar());
    
    public VEncargado() {
        initComponents();
        
    }

    public VEncargado(String RifAgencia) {
        initComponents();
        this.TF_RifAgencia.setText(RifAgencia);
        this.TF_CIEncargado.setText(this.encargado.buscarEmpleadoRegistrado(RifAgencia));
        this.RS_FechaEnc.setDatoFecha(this.encargado.FechaEncargado(RifAgencia));
        if (!(this.TF_CIEncargado.equals(""))) {
            this.Btn_Actuaizar.setEnabled(true);
            this.Btn_Eliminar.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TF_RifAgencia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TF_CIEncargado = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Btn_Buscar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Btn_Habilitar = new javax.swing.JButton();
        Btn_Nuevo = new javax.swing.JButton();
        Btn_Actuaizar = new javax.swing.JButton();
        Btn_Eliminar = new javax.swing.JButton();
        Btn_Limpiar = new javax.swing.JButton();
        Btn_Aceptar = new javax.swing.JButton();
        RS_FechaEnc = new rojeru_san.rsdate.RSDateChooser();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Sin título-2.png"))); // NOI18N
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 100));

        jLabel2.setBackground(new java.awt.Color(36, 204, 167));
        jLabel2.setFont(new java.awt.Font("Helvetica", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Encargado");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 670, 100));

        jLabel6.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(36, 204, 167));
        jLabel6.setText("RIF de la Agencia");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 180, 35));

        TF_RifAgencia.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        TF_RifAgencia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 3));
        TF_RifAgencia.setEnabled(false);
        TF_RifAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_RifAgenciaActionPerformed(evt);
            }
        });
        getContentPane().add(TF_RifAgencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 400, 35));

        jLabel7.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(36, 204, 167));
        jLabel7.setText("Cedula del Empleado");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 180, 35));

        TF_CIEncargado.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        TF_CIEncargado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 3));
        TF_CIEncargado.setEnabled(false);
        TF_CIEncargado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_CIEncargadoActionPerformed(evt);
            }
        });
        getContentPane().add(TF_CIEncargado, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 360, 35));

        jLabel8.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(36, 204, 167));
        jLabel8.setText("Fecha de Cargo");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 180, 35));

        Btn_Buscar.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/lupa(1).png"))); // NOI18N
        Btn_Buscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Btn_Buscar.setBorderPainted(false);
        Btn_Buscar.setContentAreaFilled(false);
        Btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_BuscarActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 250, 30, 30));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 2), "Opciones", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Helvetica", 1, 14), new java.awt.Color(36, 204, 167))); // NOI18N
        jPanel3.setOpaque(false);

        Btn_Habilitar.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Habilitar.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        Btn_Habilitar.setForeground(new java.awt.Color(36, 204, 167));
        Btn_Habilitar.setText("Habilitar");
        Btn_Habilitar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 204, 167), 2, true));
        Btn_Habilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_HabilitarActionPerformed(evt);
            }
        });

        Btn_Nuevo.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Nuevo.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        Btn_Nuevo.setForeground(new java.awt.Color(36, 204, 167));
        Btn_Nuevo.setText("Nuevo");
        Btn_Nuevo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 204, 167), 2, true));
        Btn_Nuevo.setEnabled(false);
        Btn_Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_NuevoActionPerformed(evt);
            }
        });

        Btn_Actuaizar.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Actuaizar.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        Btn_Actuaizar.setForeground(new java.awt.Color(36, 204, 167));
        Btn_Actuaizar.setText("Actualizar");
        Btn_Actuaizar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 204, 167), 2, true));
        Btn_Actuaizar.setEnabled(false);
        Btn_Actuaizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ActuaizarActionPerformed(evt);
            }
        });

        Btn_Eliminar.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Eliminar.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        Btn_Eliminar.setForeground(new java.awt.Color(36, 204, 167));
        Btn_Eliminar.setText("Eliminar");
        Btn_Eliminar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 204, 167), 2, true));
        Btn_Eliminar.setEnabled(false);
        Btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EliminarActionPerformed(evt);
            }
        });

        Btn_Limpiar.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Limpiar.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        Btn_Limpiar.setForeground(new java.awt.Color(36, 204, 167));
        Btn_Limpiar.setText("Limpiar");
        Btn_Limpiar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 204, 167), 2, true));
        Btn_Limpiar.setEnabled(false);
        Btn_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Btn_Habilitar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Btn_Nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Btn_Actuaizar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Btn_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Btn_Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Habilitar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Actuaizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 740, -1));

        Btn_Aceptar.setBackground(new java.awt.Color(36, 204, 167));
        Btn_Aceptar.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        Btn_Aceptar.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Aceptar.setText("Aceptar");
        Btn_Aceptar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Btn_Aceptar.setBorderPainted(false);
        Btn_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AceptarActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 570, 140, 40));

        RS_FechaEnc.setColorBackground(new java.awt.Color(36, 204, 167));
        RS_FechaEnc.setColorButtonHover(new java.awt.Color(36, 204, 167));
        RS_FechaEnc.setColorForeground(new java.awt.Color(0, 0, 0));
        RS_FechaEnc.setEnabled(false);
        RS_FechaEnc.setFuente(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        getContentPane().add(RS_FechaEnc, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 400, 35));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/fondo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TF_RifAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_RifAgenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_RifAgenciaActionPerformed

    private void TF_CIEncargadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_CIEncargadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_CIEncargadoActionPerformed

    private void Btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BuscarActionPerformed
        if (!(this.TF_CIEncargado.getText().equals(""))) {
            String nombencargado = this.encargado.buscarEmpleado(Integer.parseInt(this.TF_CIEncargado.getText()));
            if ((nombencargado.equals(""))) {
                JOptionPane.showMessageDialog(null, "Cedula no encontrada. Por favor, ingrese una cedula registrada o registre un nuevo empleado", "Advertencia", JOptionPane.WARNING_MESSAGE);
                this.TF_CIEncargado.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Empleado: "+nombencargado+" encontrado","Busqueda exitosa", JOptionPane.INFORMATION_MESSAGE);
                this.TF_CIEncargado.setEnabled(false);
                this.Btn_Nuevo.setEnabled(true);
            }
        }
    }//GEN-LAST:event_Btn_BuscarActionPerformed

    private void Btn_HabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_HabilitarActionPerformed
        this.TF_CIEncargado.setEnabled(true);
        this.RS_FechaEnc.setEnabled(true);
    }//GEN-LAST:event_Btn_HabilitarActionPerformed

    private void Btn_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_NuevoActionPerformed
        String formatoFecha = ("yyyy/MM/dd");
        SimpleDateFormat formateo = new SimpleDateFormat(formatoFecha);
        
        if (!(this.TF_CIEncargado.getText().equals("")) && !(this.RS_FechaEnc.getDatoFecha().toString().isEmpty())) {
            Date fechaDate = this.RS_FechaEnc.getDatoFecha();
            String fechaEmString = formateo.format(fechaDate);
            
            String rifag = this.TF_RifAgencia.getText();
            int cienc = Integer.parseInt(this.TF_CIEncargado.getText());           
            
            encargado.nuevoEncargado(rifag, cienc, fechaEmString);
        }
    }//GEN-LAST:event_Btn_NuevoActionPerformed

    private void Btn_ActuaizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ActuaizarActionPerformed
        String formatoFecha = ("yyyy/MM/dd");
        SimpleDateFormat formateo = new SimpleDateFormat(formatoFecha);
        
        if (!(this.TF_CIEncargado.getText().equals("")) && !(this.RS_FechaEnc.getDatoFecha().toString().isEmpty())) {
            Date fechaDate = this.RS_FechaEnc.getDatoFecha();
            String fechaEmString = formateo.format(fechaDate);
            
            String rifag = this.TF_RifAgencia.getText();
            int cienc = Integer.parseInt(this.TF_CIEncargado.getText());           
            
            encargado.actualizarEncargado(rifag, cienc, fechaEmString);
        }
    }//GEN-LAST:event_Btn_ActuaizarActionPerformed

    private void Btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EliminarActionPerformed
        if (!(this.TF_RifAgencia.getText().equals(""))) {
            String rifag = this.TF_RifAgencia.getText();         
            
            encargado.eliminarEncargado(rifag);
        }
    }//GEN-LAST:event_Btn_EliminarActionPerformed

    private void Btn_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AceptarActionPerformed
        new VAgencia().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Btn_AceptarActionPerformed

    private void Btn_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LimpiarActionPerformed

    }//GEN-LAST:event_Btn_LimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VEncargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VEncargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VEncargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VEncargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VEncargado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Aceptar;
    private javax.swing.JButton Btn_Actuaizar;
    private javax.swing.JButton Btn_Buscar;
    private javax.swing.JButton Btn_Eliminar;
    private javax.swing.JButton Btn_Habilitar;
    private javax.swing.JButton Btn_Limpiar;
    private javax.swing.JButton Btn_Nuevo;
    private rojeru_san.rsdate.RSDateChooser RS_FechaEnc;
    private javax.swing.JTextField TF_CIEncargado;
    private javax.swing.JTextField TF_RifAgencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
