/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import CRUD.CRUDInicioSesion;
import Controlador.Conexion;
import javax.swing.JOptionPane;

/**
 *
 * @author angel
 */
public class VIniciarSesión extends javax.swing.JFrame {

    /**
     * Creates new form IniciarSesión
     */
    Conexion conexion = new Conexion();
    CRUDInicioSesion rifagencia = new CRUDInicioSesion(conexion.conectar());
    int tipoUser;
    
    public VIniciarSesión() {
        initComponents();
    }
    
    public VIniciarSesión(int Tipo) {
        initComponents();
        tipoUser = Tipo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TF_Cedula = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TF_Contrasena = new javax.swing.JTextField();
        Btn_Regresar = new javax.swing.JButton();
        Btn_Ingresar = new javax.swing.JButton();
        Btn_OlvidoCont = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Sin título-2.png"))); // NOI18N
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 100));

        jLabel2.setBackground(new java.awt.Color(36, 204, 167));
        jLabel2.setFont(new java.awt.Font("Helvetica", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Iniciar Sesión");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 1000, 100));

        jLabel6.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(36, 204, 167));
        jLabel6.setText("Cedula");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 300, 35));

        TF_Cedula.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        TF_Cedula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 3));
        TF_Cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_CedulaActionPerformed(evt);
            }
        });
        getContentPane().add(TF_Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 400, 35));

        jLabel7.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(36, 204, 167));
        jLabel7.setText("Contraseña");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 300, 35));

        TF_Contrasena.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        TF_Contrasena.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 3));
        TF_Contrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_ContrasenaActionPerformed(evt);
            }
        });
        getContentPane().add(TF_Contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, 400, 35));

        Btn_Regresar.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Regresar.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        Btn_Regresar.setForeground(new java.awt.Color(36, 204, 167));
        Btn_Regresar.setText("Regresar");
        Btn_Regresar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 204, 167), 2, true));
        Btn_Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_RegresarActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 580, 140, 40));

        Btn_Ingresar.setBackground(new java.awt.Color(36, 204, 167));
        Btn_Ingresar.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        Btn_Ingresar.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Ingresar.setText("Ingresar");
        Btn_Ingresar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Btn_Ingresar.setBorderPainted(false);
        Btn_Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_IngresarActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 580, 140, 40));

        Btn_OlvidoCont.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        Btn_OlvidoCont.setForeground(new java.awt.Color(36, 204, 167));
        Btn_OlvidoCont.setText("¿Olvido la contraseña?");
        Btn_OlvidoCont.setContentAreaFilled(false);
        getContentPane().add(Btn_OlvidoCont, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, 330, 40));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/fondo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TF_CedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_CedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_CedulaActionPerformed

    private void TF_ContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_ContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_ContrasenaActionPerformed

    private void Btn_IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_IngresarActionPerformed
        if(!(this.TF_Cedula.getText().equals(""))) {            
            new VAgencia( this.rifagencia.rifEmpleado(Integer.parseInt(this.TF_Cedula.getText())) , tipoUser).setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Por favor rellene los campos faltantes", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_Btn_IngresarActionPerformed

    private void Btn_RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_RegresarActionPerformed
        new VIniciarSesión().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Btn_RegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VIniciarSesión.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VIniciarSesión.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VIniciarSesión.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VIniciarSesión.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VIniciarSesión().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Ingresar;
    private javax.swing.JButton Btn_OlvidoCont;
    private javax.swing.JButton Btn_Regresar;
    private javax.swing.JTextField TF_Cedula;
    private javax.swing.JTextField TF_Contrasena;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
