/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import CRUD.CRUDPersonal;
import Controlador.Conexion;
import Ventanas.VServicios;
import javax.swing.JOptionPane;

/**
 *
 * @author Ernesto Antonio
 */
public class VPersonal extends javax.swing.JFrame {

    Conexion conexion = new Conexion();
    CRUDPersonal per = new CRUDPersonal(conexion.conectar());
    
    /**
     * Creates new form VPersonal
     */
    public VPersonal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Btn_Agencias = new javax.swing.JButton();
        Btn_Empleados = new javax.swing.JButton();
        Btn_Clientes = new javax.swing.JButton();
        Btn_Vehiculos = new javax.swing.JButton();
        Btn_Productos = new javax.swing.JButton();
        Btn_OrdenServicios = new javax.swing.JButton();
        Btn_Facturas = new javax.swing.JButton();
        Btn_Servicios = new javax.swing.JButton();
        Btn_Actividades = new javax.swing.JButton();
        Perfiles = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TF_RifAg = new javax.swing.JTextField();
        TF_NombreEmp = new javax.swing.JTextField();
        TF_CiEmp = new javax.swing.JTextField();
        TF_Direccion = new javax.swing.JTextField();
        TF_Sueldo = new javax.swing.JTextField();
        TF_Telefono = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Btn_Habilitar = new javax.swing.JButton();
        Btn_Nuevo = new javax.swing.JButton();
        Btn_Actuaizar = new javax.swing.JButton();
        Btn_Eliminar = new javax.swing.JButton();
        Btn_Limpiar = new javax.swing.JButton();
        Btn_Buscar = new javax.swing.JButton();
        Btn_Buscar1 = new javax.swing.JButton();
        fondoBlanco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Sin título-2.png"))); // NOI18N

        Btn_Agencias.setBackground(new java.awt.Color(36, 204, 167));
        Btn_Agencias.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        Btn_Agencias.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Agencias.setText("Agencia");
        Btn_Agencias.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        Btn_Agencias.setBorderPainted(false);
        Btn_Agencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AgenciasActionPerformed(evt);
            }
        });

        Btn_Empleados.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Empleados.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        Btn_Empleados.setForeground(new java.awt.Color(36, 204, 167));
        Btn_Empleados.setText("Empleados");
        Btn_Empleados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 2));

        Btn_Clientes.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Clientes.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        Btn_Clientes.setForeground(new java.awt.Color(36, 204, 167));
        Btn_Clientes.setText("Clientes");
        Btn_Clientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 2));

        Btn_Vehiculos.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Vehiculos.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        Btn_Vehiculos.setForeground(new java.awt.Color(36, 204, 167));
        Btn_Vehiculos.setText("Vehiculos");
        Btn_Vehiculos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 2));

        Btn_Productos.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Productos.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        Btn_Productos.setForeground(new java.awt.Color(36, 204, 167));
        Btn_Productos.setText("Productos");
        Btn_Productos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 2));

        Btn_OrdenServicios.setBackground(new java.awt.Color(255, 255, 255));
        Btn_OrdenServicios.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        Btn_OrdenServicios.setForeground(new java.awt.Color(36, 204, 167));
        Btn_OrdenServicios.setText("Orden de Servicio");
        Btn_OrdenServicios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 2));
        Btn_OrdenServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_OrdenServiciosActionPerformed(evt);
            }
        });

        Btn_Facturas.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Facturas.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        Btn_Facturas.setForeground(new java.awt.Color(36, 204, 167));
        Btn_Facturas.setText("Facturas");
        Btn_Facturas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 2));

        Btn_Servicios.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Servicios.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        Btn_Servicios.setForeground(new java.awt.Color(36, 204, 167));
        Btn_Servicios.setText("Servicios");
        Btn_Servicios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 2));
        Btn_Servicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ServiciosActionPerformed(evt);
            }
        });

        Btn_Actividades.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Actividades.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        Btn_Actividades.setForeground(new java.awt.Color(36, 204, 167));
        Btn_Actividades.setText("Actividades");
        Btn_Actividades.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 2));

        Perfiles.setBackground(new java.awt.Color(255, 0, 51));
        Perfiles.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        Perfiles.setForeground(new java.awt.Color(255, 255, 255));
        Perfiles.setText("Salir");
        Perfiles.setBorderPainted(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Btn_Agencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Btn_Empleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Btn_Clientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Btn_Vehiculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Btn_Productos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Btn_OrdenServicios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Btn_Facturas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Btn_Servicios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Btn_Actividades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Perfiles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Agencias, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Servicios, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Actividades, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Empleados, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Vehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Productos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_OrdenServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Facturas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Perfiles, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 720));

        jLabel5.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(36, 204, 167));
        jLabel5.setText("RIF agencia");
        jLabel5.setToolTipText("");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 300, 35));

        jLabel6.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(36, 204, 167));
        jLabel6.setText("CI Personal");
        jLabel6.setToolTipText("");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 300, 35));

        jLabel7.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(36, 204, 167));
        jLabel7.setText("Nombre");
        jLabel7.setToolTipText("");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 300, 35));

        jLabel8.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(36, 204, 167));
        jLabel8.setText("Dirección ");
        jLabel8.setToolTipText("");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 300, 35));

        jLabel9.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(36, 204, 167));
        jLabel9.setText("Sueldo");
        jLabel9.setToolTipText("");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 300, 35));

        jLabel10.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(36, 204, 167));
        jLabel10.setText("Telefono ");
        jLabel10.setToolTipText("");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 300, 35));

        TF_RifAg.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        TF_RifAg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 3));
        TF_RifAg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_RifAgActionPerformed(evt);
            }
        });
        getContentPane().add(TF_RifAg, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, 360, 35));

        TF_NombreEmp.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        TF_NombreEmp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 3));
        TF_NombreEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_NombreEmpActionPerformed(evt);
            }
        });
        getContentPane().add(TF_NombreEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 360, 35));

        TF_CiEmp.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        TF_CiEmp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 3));
        TF_CiEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_CiEmpActionPerformed(evt);
            }
        });
        getContentPane().add(TF_CiEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 360, 35));

        TF_Direccion.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        TF_Direccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 3));
        TF_Direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_DireccionActionPerformed(evt);
            }
        });
        getContentPane().add(TF_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 360, 35));

        TF_Sueldo.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        TF_Sueldo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 3));
        TF_Sueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_SueldoActionPerformed(evt);
            }
        });
        getContentPane().add(TF_Sueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 360, 35));

        TF_Telefono.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        TF_Telefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 3));
        TF_Telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_TelefonoActionPerformed(evt);
            }
        });
        getContentPane().add(TF_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 360, 35));

        jLabel4.setBackground(new java.awt.Color(36, 204, 167));
        jLabel4.setFont(new java.awt.Font("Helvetica", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Datos del personal");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 900, 80));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 2), "Opciones", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Helvetica", 1, 14), new java.awt.Color(36, 204, 167))); // NOI18N
        jPanel3.setOpaque(false);

        Btn_Habilitar.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Habilitar.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        Btn_Habilitar.setForeground(new java.awt.Color(36, 204, 167));
        Btn_Habilitar.setText("Habilitar");
        Btn_Habilitar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 204, 167), 2, true));
        Btn_Habilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_HabilitarActionPerformed(evt);
            }
        });

        Btn_Nuevo.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Nuevo.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        Btn_Nuevo.setForeground(new java.awt.Color(36, 204, 167));
        Btn_Nuevo.setText("Nuevo");
        Btn_Nuevo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 204, 167), 2, true));
        Btn_Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_NuevoActionPerformed(evt);
            }
        });

        Btn_Actuaizar.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Actuaizar.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        Btn_Actuaizar.setForeground(new java.awt.Color(36, 204, 167));
        Btn_Actuaizar.setText("Actualizar");
        Btn_Actuaizar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 204, 167), 2, true));
        Btn_Actuaizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ActuaizarActionPerformed(evt);
            }
        });

        Btn_Eliminar.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Eliminar.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        Btn_Eliminar.setForeground(new java.awt.Color(36, 204, 167));
        Btn_Eliminar.setText("Eliminar");
        Btn_Eliminar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 204, 167), 2, true));
        Btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EliminarActionPerformed(evt);
            }
        });

        Btn_Limpiar.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Limpiar.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        Btn_Limpiar.setForeground(new java.awt.Color(36, 204, 167));
        Btn_Limpiar.setText("Limpiar");
        Btn_Limpiar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 204, 167), 2, true));
        Btn_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(Btn_Habilitar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Btn_Nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Btn_Actuaizar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Btn_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Btn_Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Habilitar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Actuaizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, 750, -1));

        Btn_Buscar.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/lupa(1).png"))); // NOI18N
        Btn_Buscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Btn_Buscar.setBorderPainted(false);
        Btn_Buscar.setContentAreaFilled(false);
        Btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_BuscarActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 170, 30, 30));

        Btn_Buscar1.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Buscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/lupa(1).png"))); // NOI18N
        Btn_Buscar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Btn_Buscar1.setBorderPainted(false);
        Btn_Buscar1.setContentAreaFilled(false);
        Btn_Buscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Buscar1ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Buscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 420, 30, 30));

        fondoBlanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/fondo.png"))); // NOI18N
        fondoBlanco.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(fondoBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_AgenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AgenciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_AgenciasActionPerformed

    private void Btn_OrdenServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_OrdenServiciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_OrdenServiciosActionPerformed

    private void Btn_ServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ServiciosActionPerformed
        new VServicios().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Btn_ServiciosActionPerformed

    private void TF_RifAgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_RifAgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_RifAgActionPerformed

    private void TF_NombreEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_NombreEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_NombreEmpActionPerformed

    private void TF_CiEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_CiEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_CiEmpActionPerformed

    private void TF_DireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_DireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_DireccionActionPerformed

    private void TF_SueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_SueldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_SueldoActionPerformed

    private void TF_TelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_TelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_TelefonoActionPerformed

    private void Btn_HabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_HabilitarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_HabilitarActionPerformed

    private void Btn_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_NuevoActionPerformed
        if (!(this.TF_CiEmp.getText().equals("")) && !(this.TF_NombreEmp.getText().equals("")) && !(this.TF_Direccion.getText().equals("")) && !(this.TF_Sueldo.getText().equals("")) && !(this.TF_Telefono.getText().equals("") && !(this.TF_RifAg.getText().equals("")))) {

            String CIEmp = this.TF_CiEmp.getText();
            String RifAg = this.TF_RifAg.getText();
            String NombreEmp = this.TF_NombreEmp.getText();
            String Direccion = this.TF_Direccion.getText();
            float Sueldo = Float.parseFloat(this.TF_Sueldo.getText());
            String Telefono = this.TF_Telefono.getText();
            

            per.nuevoPersonal(CIEmp,RifAg,NombreEmp, Direccion,Sueldo,Telefono);

        }else {
            JOptionPane.showMessageDialog(null, "Por favor rellene los campos faltantes", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_Btn_NuevoActionPerformed

    private void Btn_ActuaizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ActuaizarActionPerformed
        if (!(this.TF_CiEmp.getText().equals("")) && !(this.TF_NombreEmp.getText().equals("")) && !(this.TF_Direccion.getText().equals("")) && !(this.TF_Sueldo.getText().equals("")) && !(this.TF_Telefono.getText().equals("") && !(this.TF_RifAg.getText().equals(""))) ) {

            String CedulaCt = this.TF_CiEmp.getText();
            String RifAg = this.TF_RifAg.getText();
            String NombreCt = this.TF_NombreEmp.getText();
            String EmailCt = this.TF_Direccion.getText();
            float Sueldo = Float.parseFloat(this.TF_Sueldo.getText());
            String Telefono = this.TF_Telefono.getText();
            
            
            per.actualizarPersonal(CedulaCt,RifAg,NombreCt, EmailCt,Sueldo,Telefono);

        }else {
            JOptionPane.showMessageDialog(null, "Por favor rellene los campos faltantes", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_Btn_ActuaizarActionPerformed

    private void Btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EliminarActionPerformed
        if (!(this.TF_CiEmp.getText().equals(""))) {
            String CIEmp = this.TF_CiEmp.getText();

            per.eliminarPersonal(CIEmp);
        }
    }//GEN-LAST:event_Btn_EliminarActionPerformed

    private void Btn_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LimpiarActionPerformed
        this.TF_CiEmp.setText("");
        this.TF_NombreEmp.setText("");
        this.TF_Sueldo.setText("");
        this.TF_Direccion.setText("");
        this.TF_Telefono.setText("");
        this.TF_RifAg.setText("");
        this.TF_CiEmp.setEnabled(false);
        this.TF_NombreEmp.setEnabled(false);
        this.TF_Sueldo.setEnabled(false);
        this.TF_Direccion.setEnabled(false);
        this.TF_Telefono.setEnabled(false);
        this.TF_RifAg.setEnabled(false);
    }//GEN-LAST:event_Btn_LimpiarActionPerformed

    private void Btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BuscarActionPerformed
        if (!(this.TF_CiEmp.getText().equals(""))) {

            String[] datosAr = per.buscarPersonal(TF_CiEmp.getText());

            this.TF_NombreEmp.setText(datosAr[0]);
            this.TF_Direccion.setText(datosAr[1]);
            this.TF_Sueldo.setText(datosAr[2]);
            this.TF_Telefono.setText(datosAr[3]);
            this.TF_RifAg.setText(datosAr[4]);

        }else {
            JOptionPane.showMessageDialog(null, "Por favor rellene los campos faltantes", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        this.TF_CiEmp.setEnabled(false);
    }//GEN-LAST:event_Btn_BuscarActionPerformed

    private void Btn_Buscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Buscar1ActionPerformed
        if (!(this.TF_RifAg.getText().equals(""))) {
            String nombencargado = this.per.buscarAgencia(Integer.parseInt(this.TF_RifAg.getText()));
            if ((nombencargado.equals(""))) {
                JOptionPane.showMessageDialog(null, "Agencia no encontrada. Por favor, ingrese un RIF registrado o registre un nuevo empleado", "Advertencia", JOptionPane.WARNING_MESSAGE);
                this.TF_RifAg.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Empleado: "+nombencargado+" encontrado","Busqueda exitosa", JOptionPane.INFORMATION_MESSAGE);
                this.TF_RifAg.setEnabled(false);
                this.Btn_Nuevo.setEnabled(true);
            }
        }
    }//GEN-LAST:event_Btn_Buscar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VPersonal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Actividades;
    private javax.swing.JButton Btn_Actuaizar;
    private javax.swing.JButton Btn_Agencias;
    private javax.swing.JButton Btn_Buscar;
    private javax.swing.JButton Btn_Buscar1;
    private javax.swing.JButton Btn_Clientes;
    private javax.swing.JButton Btn_Eliminar;
    private javax.swing.JButton Btn_Empleados;
    private javax.swing.JButton Btn_Facturas;
    private javax.swing.JButton Btn_Habilitar;
    private javax.swing.JButton Btn_Limpiar;
    private javax.swing.JButton Btn_Nuevo;
    private javax.swing.JButton Btn_OrdenServicios;
    private javax.swing.JButton Btn_Productos;
    private javax.swing.JButton Btn_Servicios;
    private javax.swing.JButton Btn_Vehiculos;
    private javax.swing.JButton Perfiles;
    private javax.swing.JTextField TF_CiEmp;
    private javax.swing.JTextField TF_Direccion;
    private javax.swing.JTextField TF_NombreEmp;
    private javax.swing.JTextField TF_RifAg;
    private javax.swing.JTextField TF_Sueldo;
    private javax.swing.JTextField TF_Telefono;
    private javax.swing.JLabel fondoBlanco;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
