/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

/**
 *
 * @author angel
 */
public class VPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public VPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_Jefe = new javax.swing.JButton();
        Btn_Administrador = new javax.swing.JButton();
        Btn_Empleado = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btn_Jefe.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Jefe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/jefe(1).png"))); // NOI18N
        Btn_Jefe.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 204, 167), 3, true));
        Btn_Jefe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_JefeActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Jefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 190, 170));

        Btn_Administrador.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Administrador.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Btn_Administrador.setForeground(new java.awt.Color(36, 204, 167));
        Btn_Administrador.setText("Administrador");
        Btn_Administrador.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 204, 167), 3, true));
        Btn_Administrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AdministradorActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Administrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 560, 380, 60));

        Btn_Empleado.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Empleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/la-red.png"))); // NOI18N
        Btn_Empleado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 204, 167), 3, true));
        Btn_Empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EmpleadoActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, 190, 170));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Sin título-2.png"))); // NOI18N
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 100));

        jLabel2.setBackground(new java.awt.Color(36, 204, 167));
        jLabel2.setFont(new java.awt.Font("Helvetica", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Bienvenidos al sistema M&M");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 1000, 100));

        jLabel4.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(36, 204, 167));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Empleado");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, 190, 40));

        jLabel5.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(36, 204, 167));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Jefe");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 190, 40));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/fondo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_JefeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_JefeActionPerformed
        new VIniciarSesión(2).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Btn_JefeActionPerformed

    private void Btn_EmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EmpleadoActionPerformed
        new VIniciarSesión(3).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Btn_EmpleadoActionPerformed

    private void Btn_AdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AdministradorActionPerformed
        new VIniciarSesión(1).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Btn_AdministradorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Administrador;
    private javax.swing.JButton Btn_Empleado;
    private javax.swing.JButton Btn_Jefe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
