/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import CRUD.CRUDAgencias;
import CRUD.Productos;
import Controlador.Conexion;
import javax.swing.JOptionPane;

/**
 *
 * @author angel
 */
public class VProductos extends javax.swing.JFrame {

    Conexion conexion = new Conexion();
    Productos db = new Productos(conexion.conectar());
    
    /**
     * Creates new form VProductos
     */
    public VProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Btn_Agencias = new javax.swing.JButton();
        Btn_Empleados = new javax.swing.JButton();
        Btn_Clientes = new javax.swing.JButton();
        Btn_Vehiculos = new javax.swing.JButton();
        Btn_Productos = new javax.swing.JButton();
        Btn_OrdenServicios = new javax.swing.JButton();
        Btn_Facturas = new javax.swing.JButton();
        Btn_Servicios = new javax.swing.JButton();
        Btn_Actividades = new javax.swing.JButton();
        Perfiles = new javax.swing.JButton();
        EcoPrText = new javax.swing.JTextField();
        CodPrText = new javax.swing.JTextField();
        MinPrText = new javax.swing.JTextField();
        PrecioPrText = new javax.swing.JTextField();
        codLSButton = new javax.swing.JButton();
        Btn_Buscar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Btn_Habilitar = new javax.swing.JButton();
        Btn_Nuevo = new javax.swing.JButton();
        Btn_Actuaizar = new javax.swing.JButton();
        Btn_Eliminar = new javax.swing.JButton();
        Btn_Limpiar = new javax.swing.JButton();
        CantText = new javax.swing.JTextField();
        NombPrText = new javax.swing.JTextField();
        CodLSText = new javax.swing.JTextField();
        MaxPrText = new javax.swing.JTextField();
        DescPrText = new javax.swing.JTextField();
        FabriPrText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(36, 204, 167));
        jLabel2.setFont(new java.awt.Font("Helvetica", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Informacion sobre productos");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 900, 100));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Sin título-2.png"))); // NOI18N
        jLabel3.setOpaque(true);

        Btn_Agencias.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Agencias.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        Btn_Agencias.setForeground(new java.awt.Color(36, 204, 167));
        Btn_Agencias.setText("Agencia");
        Btn_Agencias.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 204, 167), 2, true));
        Btn_Agencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AgenciasActionPerformed(evt);
            }
        });

        Btn_Empleados.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Empleados.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        Btn_Empleados.setForeground(new java.awt.Color(36, 204, 167));
        Btn_Empleados.setText("Empleados");
        Btn_Empleados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 2));

        Btn_Clientes.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Clientes.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        Btn_Clientes.setForeground(new java.awt.Color(36, 204, 167));
        Btn_Clientes.setText("Clientes");
        Btn_Clientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 2));

        Btn_Vehiculos.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Vehiculos.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        Btn_Vehiculos.setForeground(new java.awt.Color(36, 204, 167));
        Btn_Vehiculos.setText("Vehiculos");
        Btn_Vehiculos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 2));

        Btn_Productos.setBackground(new java.awt.Color(36, 204, 167));
        Btn_Productos.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        Btn_Productos.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Productos.setText("Productos");
        Btn_Productos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        Btn_Productos.setBorderPainted(false);

        Btn_OrdenServicios.setBackground(new java.awt.Color(255, 255, 255));
        Btn_OrdenServicios.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        Btn_OrdenServicios.setForeground(new java.awt.Color(36, 204, 167));
        Btn_OrdenServicios.setText("Orden de Servicio");
        Btn_OrdenServicios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 2));
        Btn_OrdenServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_OrdenServiciosActionPerformed(evt);
            }
        });

        Btn_Facturas.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Facturas.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        Btn_Facturas.setForeground(new java.awt.Color(36, 204, 167));
        Btn_Facturas.setText("Facturas");
        Btn_Facturas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 2));

        Btn_Servicios.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Servicios.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        Btn_Servicios.setForeground(new java.awt.Color(36, 204, 167));
        Btn_Servicios.setText("Servicios");
        Btn_Servicios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 2));
        Btn_Servicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ServiciosActionPerformed(evt);
            }
        });

        Btn_Actividades.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Actividades.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        Btn_Actividades.setForeground(new java.awt.Color(36, 204, 167));
        Btn_Actividades.setText("Actividades");
        Btn_Actividades.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 2));

        Perfiles.setBackground(new java.awt.Color(255, 0, 51));
        Perfiles.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        Perfiles.setForeground(new java.awt.Color(255, 255, 255));
        Perfiles.setText("Salir");
        Perfiles.setBorderPainted(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Btn_Agencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Btn_Empleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Btn_Clientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Btn_Vehiculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Btn_Productos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Btn_OrdenServicios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Btn_Facturas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Btn_Servicios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Btn_Actividades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Perfiles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Agencias, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Servicios, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Actividades, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Empleados, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Vehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Productos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_OrdenServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Facturas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Perfiles, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 720));

        EcoPrText.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        EcoPrText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 3));
        EcoPrText.setEnabled(false);
        EcoPrText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EcoPrTextActionPerformed(evt);
            }
        });
        getContentPane().add(EcoPrText, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, 410, 35));

        CodPrText.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        CodPrText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 3));
        CodPrText.setEnabled(false);
        CodPrText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodPrTextActionPerformed(evt);
            }
        });
        getContentPane().add(CodPrText, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 360, 35));

        MinPrText.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        MinPrText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 3));
        MinPrText.setEnabled(false);
        MinPrText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinPrTextActionPerformed(evt);
            }
        });
        getContentPane().add(MinPrText, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, 410, 35));

        PrecioPrText.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        PrecioPrText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 3));
        PrecioPrText.setEnabled(false);
        PrecioPrText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecioPrTextActionPerformed(evt);
            }
        });
        getContentPane().add(PrecioPrText, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, 410, 35));

        codLSButton.setBackground(new java.awt.Color(36, 204, 167));
        codLSButton.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        codLSButton.setForeground(new java.awt.Color(255, 255, 255));
        codLSButton.setText("Linea Suministros");
        codLSButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        codLSButton.setBorderPainted(false);
        codLSButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codLSButtonActionPerformed(evt);
            }
        });
        getContentPane().add(codLSButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 217, 150, 40));

        Btn_Buscar.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/lupa(1).png"))); // NOI18N
        Btn_Buscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Btn_Buscar.setBorderPainted(false);
        Btn_Buscar.setContentAreaFilled(false);
        Btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_BuscarActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 140, 30, 30));

        jLabel4.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(36, 204, 167));
        jLabel4.setText("Descripcion del producto");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 300, 35));

        jLabel5.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(36, 204, 167));
        jLabel5.setText("Existencia del Producto");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 500, 300, 35));

        jLabel6.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(36, 204, 167));
        jLabel6.setText("Maximo de producto");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 300, 35));

        jLabel7.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(36, 204, 167));
        jLabel7.setText("Precio del producto");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 300, 35));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 2), "Opciones", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Helvetica", 1, 14), new java.awt.Color(36, 204, 167))); // NOI18N
        jPanel3.setOpaque(false);

        Btn_Habilitar.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Habilitar.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        Btn_Habilitar.setForeground(new java.awt.Color(36, 204, 167));
        Btn_Habilitar.setText("Habilitar");
        Btn_Habilitar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 204, 167), 2, true));
        Btn_Habilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_HabilitarActionPerformed(evt);
            }
        });

        Btn_Nuevo.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Nuevo.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        Btn_Nuevo.setForeground(new java.awt.Color(36, 204, 167));
        Btn_Nuevo.setText("Nuevo");
        Btn_Nuevo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 204, 167), 2, true));
        Btn_Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_NuevoActionPerformed(evt);
            }
        });

        Btn_Actuaizar.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Actuaizar.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        Btn_Actuaizar.setForeground(new java.awt.Color(36, 204, 167));
        Btn_Actuaizar.setText("Actualizar");
        Btn_Actuaizar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 204, 167), 2, true));
        Btn_Actuaizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ActuaizarActionPerformed(evt);
            }
        });

        Btn_Eliminar.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Eliminar.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        Btn_Eliminar.setForeground(new java.awt.Color(36, 204, 167));
        Btn_Eliminar.setText("Eliminar");
        Btn_Eliminar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 204, 167), 2, true));
        Btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EliminarActionPerformed(evt);
            }
        });

        Btn_Limpiar.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Limpiar.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        Btn_Limpiar.setForeground(new java.awt.Color(36, 204, 167));
        Btn_Limpiar.setText("Limpiar");
        Btn_Limpiar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 204, 167), 2, true));
        Btn_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(Btn_Habilitar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Btn_Nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Btn_Actuaizar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Btn_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Btn_Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Habilitar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Actuaizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 580, 750, -1));

        CantText.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        CantText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 3));
        CantText.setEnabled(false);
        CantText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantTextActionPerformed(evt);
            }
        });
        getContentPane().add(CantText, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 500, 410, 35));

        NombPrText.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        NombPrText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 3));
        NombPrText.setEnabled(false);
        NombPrText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombPrTextActionPerformed(evt);
            }
        });
        getContentPane().add(NombPrText, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, 410, 35));

        CodLSText.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        CodLSText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 3));
        CodLSText.setEnabled(false);
        CodLSText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodLSTextActionPerformed(evt);
            }
        });
        getContentPane().add(CodLSText, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, 250, 35));

        MaxPrText.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        MaxPrText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 3));
        MaxPrText.setEnabled(false);
        MaxPrText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaxPrTextActionPerformed(evt);
            }
        });
        getContentPane().add(MaxPrText, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, 410, 35));

        DescPrText.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        DescPrText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 3));
        DescPrText.setEnabled(false);
        DescPrText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescPrTextActionPerformed(evt);
            }
        });
        getContentPane().add(DescPrText, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, 410, 35));

        FabriPrText.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        FabriPrText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 3));
        FabriPrText.setEnabled(false);
        FabriPrText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FabriPrTextActionPerformed(evt);
            }
        });
        getContentPane().add(FabriPrText, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, 410, 35));

        jLabel8.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(36, 204, 167));
        jLabel8.setText("Codigo Producto");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 300, 35));

        jLabel9.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(36, 204, 167));
        jLabel9.setText("Nombre Producto");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 300, 35));

        jLabel10.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(36, 204, 167));
        jLabel10.setText("Cod Linea Suministro");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 300, 35));

        jLabel11.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(36, 204, 167));
        jLabel11.setText("Minimo de producto");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 300, 35));

        jLabel12.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(36, 204, 167));
        jLabel12.setText("Producto Ecologico");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 300, 35));

        jLabel13.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(36, 204, 167));
        jLabel13.setText("FabriPr!!!!");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 300, 35));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/fondo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_AgenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AgenciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_AgenciasActionPerformed

    private void Btn_ServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ServiciosActionPerformed
        new VServicios().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Btn_ServiciosActionPerformed

    private void Btn_OrdenServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_OrdenServiciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_OrdenServiciosActionPerformed

    private void EcoPrTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EcoPrTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EcoPrTextActionPerformed

    private void CodPrTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodPrTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodPrTextActionPerformed

    private void MinPrTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinPrTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MinPrTextActionPerformed

    private void PrecioPrTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioPrTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioPrTextActionPerformed

    private void Btn_ActuaizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ActuaizarActionPerformed
        if (!(this.CodPrText.getText().equals("")) && !(this.MinPrText.getText().equals("")) && !(this.PrecioPrText.getText().equals("")) && !(this.EcoPrText.getText().equals(""))
                && !(this.NombPrText.getText().equals("")) && !(this.MaxPrText.getText().equals("")) && !(this.CodLSText.getText().equals(""))
                && !(this.DescPrText.getText().equals("")) && !(this.FabriPrText.getText().equals("")) && !(this.CantText.getText().equals(""))) {
            
            try {
                int max = Integer.parseInt(this.MaxPrText.getText());
                int min = Integer.parseInt(this.MinPrText.getText());
                int cant = Integer.parseInt(this.CantText.getText());
                
                db.updateProducto(this.CodPrText.getText(), this.NombPrText.getText(), this.CodLSText.getText(), max, min, this.PrecioPrText.getText(), 
                        this.EcoPrText.getText(), this.DescPrText.getText(), this.FabriPrText.getText(), cant);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error: Maximo,Minimo y Cantidad deben ser numeros", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }

        }else {
            JOptionPane.showMessageDialog(null, "Por favor rellene los campos faltantes", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_Btn_ActuaizarActionPerformed

    private void Btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BuscarActionPerformed
        if (!(this.CodPrText.getText().equals(""))) {
            
            String[] datoAr = db.obtenerProducto(this.CodPrText.getText());
            
            this.NombPrText.setText(datoAr[0]);
            this.CodLSText.setText(datoAr[1]);
            this.MaxPrText.setText(datoAr[2]);
            this.MinPrText.setText(datoAr[3]);
            this.PrecioPrText.setText(datoAr[4]);
            this.EcoPrText.setText(datoAr[5]);
            this.DescPrText.setText(datoAr[6]);
            this.FabriPrText.setText(datoAr[7]);
            this.CantText.setText(datoAr[8]);
   
        }else {
            JOptionPane.showMessageDialog(null, "Por favor rellene los campos faltantes", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        if (!(this.MinPrText.getText().equals("")) && !(this.PrecioPrText.getText().equals("")) && !(this.EcoPrText.getText().equals(""))) {
            this.CodPrText.setEnabled(false);
        }
        else {
            JOptionPane.showMessageDialog(null, "Registro no encontrado","Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_Btn_BuscarActionPerformed

    private void Btn_HabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_HabilitarActionPerformed
        this.CodPrText.setEnabled(true);
        this.NombPrText.setEnabled(true);
        this.CodLSText.setEnabled(true);
        this.MaxPrText.setEnabled(true);
        this.MinPrText.setEnabled(true);
        this.PrecioPrText.setEnabled(true);
        this.EcoPrText.setEnabled(true);
        this.DescPrText.setEnabled(true);
        this.FabriPrText.setEnabled(true);
        this.CantText.setEnabled(true);
    }//GEN-LAST:event_Btn_HabilitarActionPerformed

    private void Btn_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LimpiarActionPerformed
        this.CodPrText.setText("");
        this.NombPrText.setText("");
        this.CodLSText.setText("");
        this.MaxPrText.setText("");
        this.MinPrText.setText("");
        this.PrecioPrText.setText("");
        this.EcoPrText.setText("");
        this.DescPrText.setText("");
        this.FabriPrText.setText("");
        this.CantText.setText("");
        this.CodPrText.setEnabled(false);
        this.NombPrText.setEnabled(false);
        this.CodLSText.setEnabled(false);
        this.MaxPrText.setEnabled(false);
        this.MinPrText.setEnabled(false);
        this.PrecioPrText.setEnabled(false);
        this.EcoPrText.setEnabled(false);
        this.DescPrText.setEnabled(false);
        this.FabriPrText.setEnabled(false);
        this.CantText.setEnabled(false);
    }//GEN-LAST:event_Btn_LimpiarActionPerformed

    private void Btn_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_NuevoActionPerformed
        if (!(this.CodPrText.getText().equals("")) && !(this.MinPrText.getText().equals("")) && !(this.PrecioPrText.getText().equals("")) && !(this.EcoPrText.getText().equals(""))
                && !(this.NombPrText.getText().equals("")) && !(this.MaxPrText.getText().equals("")) && !(this.CodLSText.getText().equals(""))
                && !(this.DescPrText.getText().equals("")) && !(this.FabriPrText.getText().equals("")) && !(this.CantText.getText().equals(""))) {
            try {
                int max = Integer.parseInt(this.MaxPrText.getText());
                int min = Integer.parseInt(this.MinPrText.getText());
                int cant = Integer.parseInt(this.CantText.getText());
                
                db.agregarProductor(this.CodPrText.getText(), this.NombPrText.getText(), this.CodLSText.getText(), max, min, this.PrecioPrText.getText(), 
                        this.EcoPrText.getText(), this.DescPrText.getText(), this.FabriPrText.getText(), cant);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error: Maximo,Minimo y Cantidad deben ser numeros", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }
            
        }else {
            JOptionPane.showMessageDialog(null, "Por favor rellene los campos faltantes", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_Btn_NuevoActionPerformed

    private void Btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EliminarActionPerformed
        if (!(this.CodPrText.getText().equals(""))) {
            db.deletePr(this.CodPrText.getText());
        }else{
            JOptionPane.showMessageDialog(null, "Rellene el campo Codigo Producto", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_Btn_EliminarActionPerformed

    private void codLSButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codLSButtonActionPerformed
        new VLineaS().setVisible(true);
    }//GEN-LAST:event_codLSButtonActionPerformed

    private void CantTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantTextActionPerformed

    private void NombPrTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombPrTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombPrTextActionPerformed

    private void CodLSTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodLSTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodLSTextActionPerformed

    private void MaxPrTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaxPrTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaxPrTextActionPerformed

    private void DescPrTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescPrTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescPrTextActionPerformed

    private void FabriPrTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FabriPrTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FabriPrTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Actividades;
    private javax.swing.JButton Btn_Actuaizar;
    private javax.swing.JButton Btn_Agencias;
    private javax.swing.JButton Btn_Buscar;
    private javax.swing.JButton Btn_Clientes;
    private javax.swing.JButton Btn_Eliminar;
    private javax.swing.JButton Btn_Empleados;
    private javax.swing.JButton Btn_Facturas;
    private javax.swing.JButton Btn_Habilitar;
    private javax.swing.JButton Btn_Limpiar;
    private javax.swing.JButton Btn_Nuevo;
    private javax.swing.JButton Btn_OrdenServicios;
    private javax.swing.JButton Btn_Productos;
    private javax.swing.JButton Btn_Servicios;
    private javax.swing.JButton Btn_Vehiculos;
    private javax.swing.JTextField CantText;
    private javax.swing.JTextField CodLSText;
    private javax.swing.JTextField CodPrText;
    private javax.swing.JTextField DescPrText;
    private javax.swing.JTextField EcoPrText;
    private javax.swing.JTextField FabriPrText;
    private javax.swing.JTextField MaxPrText;
    private javax.swing.JTextField MinPrText;
    private javax.swing.JTextField NombPrText;
    private javax.swing.JButton Perfiles;
    private javax.swing.JTextField PrecioPrText;
    private javax.swing.JButton codLSButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
