/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import CRUD.CRUDVehiculos;
import Controlador.Conexion;
import Ventanas.VServicios;
import java.sql.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Ernesto Antonio
 */
public class VVehiculos extends javax.swing.JFrame {

    Conexion conexion = new Conexion();
    CRUDVehiculos veh = new CRUDVehiculos(conexion.conectar());
    
    /**
     * Creates new form VVehiculos
     */
    public VVehiculos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Btn_Agencias = new javax.swing.JButton();
        Btn_Empleados = new javax.swing.JButton();
        Btn_Clientes = new javax.swing.JButton();
        Btn_Vehiculos = new javax.swing.JButton();
        Btn_Productos = new javax.swing.JButton();
        Btn_OrdenServicios = new javax.swing.JButton();
        Btn_Facturas = new javax.swing.JButton();
        Btn_Servicios = new javax.swing.JButton();
        Btn_Actividades = new javax.swing.JButton();
        Perfiles = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TF_ModVeh = new javax.swing.JTextField();
        TF_PlacVeh = new javax.swing.JTextField();
        TF_CodVeh = new javax.swing.JTextField();
        TF_AceiteUt = new javax.swing.JTextField();
        TF_MarcaVeh = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Btn_Habilitar = new javax.swing.JButton();
        Btn_Nuevo = new javax.swing.JButton();
        Btn_Actuaizar = new javax.swing.JButton();
        Btn_Eliminar = new javax.swing.JButton();
        Btn_Limpiar = new javax.swing.JButton();
        Btn_Buscar = new javax.swing.JButton();
        TF_CICliente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Btn_Buscar1 = new javax.swing.JButton();
        RS_FechaAdq = new rojeru_san.rsdate.RSDateChooser();
        fondoBlanco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Sin título-2.png"))); // NOI18N

        Btn_Agencias.setBackground(new java.awt.Color(36, 204, 167));
        Btn_Agencias.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        Btn_Agencias.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Agencias.setText("Agencia");
        Btn_Agencias.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        Btn_Agencias.setBorderPainted(false);
        Btn_Agencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AgenciasActionPerformed(evt);
            }
        });

        Btn_Empleados.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Empleados.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        Btn_Empleados.setForeground(new java.awt.Color(36, 204, 167));
        Btn_Empleados.setText("Empleados");
        Btn_Empleados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 2));

        Btn_Clientes.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Clientes.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        Btn_Clientes.setForeground(new java.awt.Color(36, 204, 167));
        Btn_Clientes.setText("Clientes");
        Btn_Clientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 2));

        Btn_Vehiculos.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Vehiculos.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        Btn_Vehiculos.setForeground(new java.awt.Color(36, 204, 167));
        Btn_Vehiculos.setText("Vehiculos");
        Btn_Vehiculos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 2));

        Btn_Productos.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Productos.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        Btn_Productos.setForeground(new java.awt.Color(36, 204, 167));
        Btn_Productos.setText("Productos");
        Btn_Productos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 2));

        Btn_OrdenServicios.setBackground(new java.awt.Color(255, 255, 255));
        Btn_OrdenServicios.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        Btn_OrdenServicios.setForeground(new java.awt.Color(36, 204, 167));
        Btn_OrdenServicios.setText("Orden de Servicio");
        Btn_OrdenServicios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 2));
        Btn_OrdenServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_OrdenServiciosActionPerformed(evt);
            }
        });

        Btn_Facturas.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Facturas.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        Btn_Facturas.setForeground(new java.awt.Color(36, 204, 167));
        Btn_Facturas.setText("Facturas");
        Btn_Facturas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 2));

        Btn_Servicios.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Servicios.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        Btn_Servicios.setForeground(new java.awt.Color(36, 204, 167));
        Btn_Servicios.setText("Servicios");
        Btn_Servicios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 2));
        Btn_Servicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ServiciosActionPerformed(evt);
            }
        });

        Btn_Actividades.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Actividades.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        Btn_Actividades.setForeground(new java.awt.Color(36, 204, 167));
        Btn_Actividades.setText("Actividades");
        Btn_Actividades.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 2));

        Perfiles.setBackground(new java.awt.Color(255, 0, 51));
        Perfiles.setFont(new java.awt.Font("Helvetica", 1, 17)); // NOI18N
        Perfiles.setForeground(new java.awt.Color(255, 255, 255));
        Perfiles.setText("Salir");
        Perfiles.setBorderPainted(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Btn_Agencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Btn_Empleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Btn_Clientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Btn_Vehiculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Btn_Productos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Btn_OrdenServicios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Btn_Facturas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Btn_Servicios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Btn_Actividades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Perfiles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Agencias, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Servicios, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Actividades, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Empleados, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Vehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Productos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_OrdenServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Facturas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Perfiles, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 720));

        jLabel5.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(36, 204, 167));
        jLabel5.setText("CI Cliente");
        jLabel5.setToolTipText("");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 300, 35));

        jLabel6.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(36, 204, 167));
        jLabel6.setText("Codigo del Vehículo");
        jLabel6.setToolTipText("");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 300, 35));

        jLabel7.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(36, 204, 167));
        jLabel7.setText("Placa vehiculo");
        jLabel7.setToolTipText("");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 300, 35));

        jLabel8.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(36, 204, 167));
        jLabel8.setText("Aceite utilizado");
        jLabel8.setToolTipText("");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 300, 35));

        jLabel9.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(36, 204, 167));
        jLabel9.setText("Fecha de adquisición");
        jLabel9.setToolTipText("");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 230, 35));

        jLabel10.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(36, 204, 167));
        jLabel10.setText("Marca del vehículo");
        jLabel10.setToolTipText("");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 300, 35));

        TF_ModVeh.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        TF_ModVeh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 3));
        TF_ModVeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_ModVehActionPerformed(evt);
            }
        });
        getContentPane().add(TF_ModVeh, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, 360, 35));

        TF_PlacVeh.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        TF_PlacVeh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 3));
        TF_PlacVeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_PlacVehActionPerformed(evt);
            }
        });
        getContentPane().add(TF_PlacVeh, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 360, 35));

        TF_CodVeh.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        TF_CodVeh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 3));
        TF_CodVeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_CodVehActionPerformed(evt);
            }
        });
        getContentPane().add(TF_CodVeh, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 360, 35));

        TF_AceiteUt.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        TF_AceiteUt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 3));
        TF_AceiteUt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_AceiteUtActionPerformed(evt);
            }
        });
        getContentPane().add(TF_AceiteUt, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 360, 35));

        TF_MarcaVeh.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        TF_MarcaVeh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 3));
        TF_MarcaVeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_MarcaVehActionPerformed(evt);
            }
        });
        getContentPane().add(TF_MarcaVeh, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 360, 35));

        jLabel4.setBackground(new java.awt.Color(36, 204, 167));
        jLabel4.setFont(new java.awt.Font("Helvetica", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Datos del Vehiculo");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 900, 80));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 2), "Opciones", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Helvetica", 1, 14), new java.awt.Color(36, 204, 167))); // NOI18N
        jPanel3.setOpaque(false);

        Btn_Habilitar.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Habilitar.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        Btn_Habilitar.setForeground(new java.awt.Color(36, 204, 167));
        Btn_Habilitar.setText("Habilitar");
        Btn_Habilitar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 204, 167), 2, true));
        Btn_Habilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_HabilitarActionPerformed(evt);
            }
        });

        Btn_Nuevo.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Nuevo.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        Btn_Nuevo.setForeground(new java.awt.Color(36, 204, 167));
        Btn_Nuevo.setText("Nuevo");
        Btn_Nuevo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 204, 167), 2, true));
        Btn_Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_NuevoActionPerformed(evt);
            }
        });

        Btn_Actuaizar.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Actuaizar.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        Btn_Actuaizar.setForeground(new java.awt.Color(36, 204, 167));
        Btn_Actuaizar.setText("Actualizar");
        Btn_Actuaizar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 204, 167), 2, true));
        Btn_Actuaizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ActuaizarActionPerformed(evt);
            }
        });

        Btn_Eliminar.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Eliminar.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        Btn_Eliminar.setForeground(new java.awt.Color(36, 204, 167));
        Btn_Eliminar.setText("Eliminar");
        Btn_Eliminar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 204, 167), 2, true));
        Btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EliminarActionPerformed(evt);
            }
        });

        Btn_Limpiar.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Limpiar.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        Btn_Limpiar.setForeground(new java.awt.Color(36, 204, 167));
        Btn_Limpiar.setText("Limpiar");
        Btn_Limpiar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(36, 204, 167), 2, true));
        Btn_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(Btn_Habilitar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Btn_Nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Btn_Actuaizar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Btn_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Btn_Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Habilitar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Actuaizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 580, 750, -1));

        Btn_Buscar.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/lupa(1).png"))); // NOI18N
        Btn_Buscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Btn_Buscar.setBorderPainted(false);
        Btn_Buscar.setContentAreaFilled(false);
        Btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_BuscarActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 150, 30, 30));

        TF_CICliente.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        TF_CICliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(36, 204, 167), 3));
        TF_CICliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_CIClienteActionPerformed(evt);
            }
        });
        getContentPane().add(TF_CICliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, 360, 35));

        jLabel11.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(36, 204, 167));
        jLabel11.setText("Modelo del vehículo");
        jLabel11.setToolTipText("");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 300, 35));

        Btn_Buscar1.setBackground(new java.awt.Color(255, 255, 255));
        Btn_Buscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/lupa(1).png"))); // NOI18N
        Btn_Buscar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Btn_Buscar1.setBorderPainted(false);
        Btn_Buscar1.setContentAreaFilled(false);
        Btn_Buscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Buscar1ActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Buscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 450, 30, 30));

        RS_FechaAdq.setColorBackground(new java.awt.Color(36, 204, 167));
        RS_FechaAdq.setColorButtonHover(new java.awt.Color(36, 204, 167));
        RS_FechaAdq.setColorForeground(new java.awt.Color(0, 0, 0));
        RS_FechaAdq.setFuente(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        getContentPane().add(RS_FechaAdq, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 360, 35));

        fondoBlanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/fondo.png"))); // NOI18N
        getContentPane().add(fondoBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_AgenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AgenciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_AgenciasActionPerformed

    private void Btn_OrdenServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_OrdenServiciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_OrdenServiciosActionPerformed

    private void Btn_ServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ServiciosActionPerformed
        new VServicios().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Btn_ServiciosActionPerformed

    private void TF_CodVehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_CodVehActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_CodVehActionPerformed

    private void TF_PlacVehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_PlacVehActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_PlacVehActionPerformed

    private void TF_ModVehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_ModVehActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_ModVehActionPerformed

    private void TF_AceiteUtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_AceiteUtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_AceiteUtActionPerformed

    private void TF_MarcaVehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_MarcaVehActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_MarcaVehActionPerformed

    private void Btn_ActuaizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ActuaizarActionPerformed
        String formatoFecha = ("yyyy/MM/dd");
        SimpleDateFormat formateo = new SimpleDateFormat(formatoFecha);
        
        if (!(this.TF_CodVeh.getText().equals("")) && !(this.TF_PlacVeh.getText().equals("")) && !(this.TF_AceiteUt.getText().equals("")) && !(this.RS_FechaAdq.getDatoFecha().toString().isEmpty()) && !(this.TF_MarcaVeh.getText().equals("") && !(this.TF_ModVeh.getText().equals(""))) ) {

                java.util.Date fechaDate = this.RS_FechaAdq.getDatoFecha();
                String FechaAdq = formateo.format(fechaDate);
            
            
                String CodVeh = this.TF_CodVeh.getText();
                String CICliente = this.TF_CICliente.getText();
                String PlacaVeh = this.TF_PlacVeh.getText(); 
                String AceiteUt = this.TF_AceiteUt.getText();
                String MarcaVeh = this.TF_MarcaVeh.getText();
                String ModeloVeh = this.TF_ModVeh.getText();
               

                veh.actualizarVehiculos(CodVeh,CICliente,PlacaVeh, AceiteUt,FechaAdq,MarcaVeh,ModeloVeh);

            }else {
                JOptionPane.showMessageDialog(null, "Por favor rellene los campos faltantes", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_Btn_ActuaizarActionPerformed

    private void Btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BuscarActionPerformed
        String formatoFecha = ("yyyy/MM/dd");
        SimpleDateFormat formateo = new SimpleDateFormat(formatoFecha);
        
        if (!(this.TF_CodVeh.getText().equals(""))) {
            java.util.Date fechaDate = this.RS_FechaAdq.getDatoFecha();
            String FechaAdq= formateo.format(fechaDate);            
            
            String[] datosAr = veh.buscarVehiculos(TF_CodVeh.getText());
            
            this.TF_PlacVeh.setText(datosAr[0]);
            this.TF_AceiteUt.setText(datosAr[1]);
            this.RS_FechaAdq.setDatoFecha(this.veh.FechaAdq(FechaAdq));
            this.TF_MarcaVeh.setText(datosAr[2]);
            this.TF_ModVeh.setText(datosAr[3]);
            this.TF_CICliente.setText(datosAr[4]);

        }else {
            JOptionPane.showMessageDialog(null, "Por favor rellene los campos faltantes", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        this.TF_CodVeh.setEnabled(false);
    }//GEN-LAST:event_Btn_BuscarActionPerformed

    private void Btn_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_NuevoActionPerformed
        String formatoFecha = ("yyyy/MM/dd");
        SimpleDateFormat formateo = new SimpleDateFormat(formatoFecha);
        
        
        if (!(this.TF_CodVeh.getText().equals("")) && !(this.TF_PlacVeh.getText().equals("")) && !(this.TF_AceiteUt.getText().equals("")) && !(this.RS_FechaAdq.getDatoFecha().toString().isEmpty()) && !(this.TF_MarcaVeh.getText().equals("") && !(this.TF_ModVeh.getText().equals("")))) {
            java.util.Date fechaDate = this.RS_FechaAdq.getDatoFecha();
            String FechaAdq = formateo.format(fechaDate);
            
            
            String CodVeh = this.TF_CodVeh.getText();
            String CICliente = this.TF_CICliente.getText();
            String PlacaVeh = this.TF_PlacVeh.getText(); 
            String AceiteUt = this.TF_AceiteUt.getText();

            String MarcaVeh = this.TF_MarcaVeh.getText();
            String ModeloVeh = this.TF_ModVeh.getText();
            
            
           veh.nuevoVehiculos(CodVeh,CICliente,PlacaVeh, AceiteUt,FechaAdq,MarcaVeh,ModeloVeh);
            
        }else {
            JOptionPane.showMessageDialog(null, "Por favor rellene los campos faltantes", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_Btn_NuevoActionPerformed

    private void Btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EliminarActionPerformed
        if (!(this.TF_CodVeh.getText().equals(""))) {
            String CodVeh = this.TF_CodVeh.getText();

            veh.eliminarVehiculo(CodVeh);
        }
    }//GEN-LAST:event_Btn_EliminarActionPerformed

    private void Btn_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LimpiarActionPerformed
        this.TF_CodVeh.setText("");
        this.TF_PlacVeh.setText("");
        this.RS_FechaAdq.setDatoFecha(null);
        this.TF_AceiteUt.setText("");
        this.TF_MarcaVeh.setText("");
        this.TF_ModVeh.setText("");
        this.TF_CodVeh.setEnabled(false);
        this.TF_PlacVeh.setEnabled(false);
        this.RS_FechaAdq.setEnabled(false);
        this.TF_AceiteUt.setEnabled(false);
        this.TF_MarcaVeh.setEnabled(false);
        this.TF_ModVeh.setEnabled(false);
        this.TF_CICliente.setEnabled(false);
    }//GEN-LAST:event_Btn_LimpiarActionPerformed

    private void Btn_HabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_HabilitarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_HabilitarActionPerformed

    private void TF_CIClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_CIClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_CIClienteActionPerformed

    private void Btn_Buscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Buscar1ActionPerformed
         if (!(this.TF_CICliente.getText().equals(""))) {
            String NombreCt = this.veh.buscarCliente(Integer.parseInt(this.TF_CICliente.getText()));
            if ((NombreCt.equals(""))) {
                JOptionPane.showMessageDialog(null, "Cliente no encontrado. Por favor, ingrese una cedula registrada o registre un nuevo vehiculo", "Advertencia", JOptionPane.WARNING_MESSAGE);
                this.TF_CICliente.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Cliente: "+NombreCt+" encontrado","Busqueda exitosa", JOptionPane.INFORMATION_MESSAGE);
                this.TF_CICliente.setEnabled(false);
                this.Btn_Nuevo.setEnabled(true);
            }
        }
    }//GEN-LAST:event_Btn_Buscar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VVehiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Actividades;
    private javax.swing.JButton Btn_Actuaizar;
    private javax.swing.JButton Btn_Agencias;
    private javax.swing.JButton Btn_Buscar;
    private javax.swing.JButton Btn_Buscar1;
    private javax.swing.JButton Btn_Clientes;
    private javax.swing.JButton Btn_Eliminar;
    private javax.swing.JButton Btn_Empleados;
    private javax.swing.JButton Btn_Facturas;
    private javax.swing.JButton Btn_Habilitar;
    private javax.swing.JButton Btn_Limpiar;
    private javax.swing.JButton Btn_Nuevo;
    private javax.swing.JButton Btn_OrdenServicios;
    private javax.swing.JButton Btn_Productos;
    private javax.swing.JButton Btn_Servicios;
    private javax.swing.JButton Btn_Vehiculos;
    private javax.swing.JButton Perfiles;
    private rojeru_san.rsdate.RSDateChooser RS_FechaAdq;
    private javax.swing.JTextField TF_AceiteUt;
    private javax.swing.JTextField TF_CICliente;
    private javax.swing.JTextField TF_CodVeh;
    private javax.swing.JTextField TF_MarcaVeh;
    private javax.swing.JTextField TF_ModVeh;
    private javax.swing.JTextField TF_PlacVeh;
    private javax.swing.JLabel fondoBlanco;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
